### ISSUE TITLE
Vendetta crash during YouTube link being sent in chat

### ISSUE THREAD

**Issue by Rairof** [Angelix1/VP#2]
Don't know why this happens but it's really annoying. Hope you can fix it, @Angelix1 
I didn't had any issues with ur message logger plugin for months until now...:(
![Screenshot_2023-12-03-03-57-10-847_dev beefers vendetta-edit](https://github.com/Angelix1/VP/assets/107706560/0989e576-28b8-4903-805b-1b9e6a6e315d)
![Screenshot_2023-12-03-04-09-11-639_dev beefers vendetta-edit](https://github.com/Angelix1/VP/assets/107706560/17a30d1e-4029-4e5a-a1d0-8a98ca959ba5)

**Comment by Rairof** [comment]
It's been happening for more than a month but didn't knew this plugin was causing the issue so couldn't report the issue earlier. 
Apologies for the delay.

**Comment by Angelix1** [comment]
i know this issue exist, i still didnt find any fix for it

**Comment by Rairof** [comment]
Oh, maybe you should join in vendetta discord server and ask for help there to know more about the issue... I'm not much of a coder so idk how all this works but there are other people who might be able to help you there!!.
Love ur logger btw

**Comment by Angelix1** [comment]
i already in the discord server

**Comment by Rairof** [comment]
Ah okay sorry. It's alright, take your time on finding the issue, just wanted to say it in here. Thanks.

**Comment by Rairof** [comment]
I mostly like your logger because it provides all the useful functions without any setbacks unlike NoDelete plugin in vendetta server.

Reasons I don't use Nodelete plugin-
• doesn't log editted messages
• doesn't have any option to dismiss logged messages without a full app restart (which sucks)
• doesn't log your own messages
• can't change colours or "(deleted)" tag to whatever we want when messages gets logged

All these aren't a issue in your plugin hence I like yours one more then NoDelete plugin. ❤️

**Comment by Angelix1** [comment]
ty

**Comment by Rairof** [comment]
While ur at it, can you also look into why it doesn't log editted messages that only has a media or link sent first then editted to add text to that message?

Editted message with only media-
![Screenshot_2023-12-03-09-18-04-067_dev beefers vendetta-edit](https://github.com/Angelix1/VP/assets/107706560/8147baf0-97da-4b4c-adfe-9a706925a2ec)

Editted message with added text to the media-
![Screenshot_2023-12-03-09-16-18-441_dev beefers vendetta-edit](https://github.com/Angelix1/VP/assets/107706560/bff20535-4e66-4122-8061-711ed867293b)

**Comment by Rairof** [comment]
Also a small tabsv2 UI design issue that I think can be fixed with this code snippet by nexpid...

Current state in tabsv2 layout-
![Screenshot_2023-12-03-09-22-15-962_dev beefers vendetta-edit](https://github.com/Angelix1/VP/assets/107706560/8c121071-3417-4ae6-9c97-bb91389aab76)

Credit to nexpid for this-
![Screenshot_2023-12-03-09-22-58-955_dev beefers vendetta-edit](https://github.com/Angelix1/VP/assets/107706560/f40bbd94-e156-4cce-a0c3-de1663db6ad7)

## Row that automatically adapts to Tabs v2
i moved this to an npm package! ```sh
pnpm i @nexpid/vdp-shared```

 ```tsx
import { RedesignRow } from "@nexpid/vdp-shared";

export function SomeComponent({ isCool }: { isCool: boolean }) {
  return (
    <RedesignRow
      label={"Do Something Awesome"}
      icon={getAssetIDByName("ic_cog_24px")}
      onPress={() => {
        if (!isCool)
          showToast("You're not cool enough!", getAssetIDByName("Small"));
        else showToast("Awesome thing");
      }}
    />
  );
}
```

**Comment by Angelix1** [comment]
i still use old tab, so tabv2 will gonna be unsupported for now,
also use v0.305 and here's the link https://angelix1.github.io/VP/antied
and it should fix these issue

Added:
- Support for other plugin to Bypass Logging (`otherPluginBypass`)

FIX:
- Inconsistent Remove Edit button.
- Hopefully `Fix Invalid Integer ???`.
- Unable Dismiss Message that sent as ephemeral by default.

Other:
- Removed AlwaysAdd option

Known Inconsistent Issue:
- Embedded Message accidentally not logged
